export enum Cookie {
  SessionId = "session_id",
}

export enum PriceRange {
  BUDGET = "$",
  LOW = "$$",
  MEDIUM = "$$$",
  HIGH = "$$$$",
}

export enum Cuisine {
  Italian = "Italian",
  Chinese = "Chinese",
  Mexican = "Mexican",
  Japanese = "Japanese",
  Indian = "Indian",
  Thai = "Thai",
  French = "French",
  Mediterranean = "Mediterranean",
  American = "American",
  Korean = "Korean",
  Spanish = "Spanish",
  Vietnamese = "Vietnamese",
  Greek = "Greek",
  Lebanese = "Lebanese",
  Turkish = "Turkish",
  Brazilian = "Brazilian",
  Moroccan = "Moroccan",
  Ethiopian = "Ethiopian",
  Peruvian = "Peruvian",
  German = "German",
}

export enum FoodAllergen {
  Almonds = "Almonds",
  Anchovy = "Anchovy",
  Bass = "Bass",
  Bluefish = "Bluefish",
  Bonito = "Bonito",
  Butterfish = "Butterfish",
  Carp = "Carp",
  Cashews = "Cashews",
  Catfish = "Catfish",
  Celery = "Celery",
  Chestnuts = "Chestnuts",
  Coconut = "Coconut",
  Cod = "Cod",
  Crab = "Crab",
  Crustaceans = "Crustaceans",
  Eel = "Eel",
  Eggs = "Eggs",
  Fish = "Fish",
  Flounder = "Flounder",
  Gluten = "Gluten",
  Grouper = "Grouper",
  Haddock = "Haddock",
  Halibut = "Halibut",
  Hazelnuts = "Hazelnuts",
  Herring = "Herring",
  Lobster = "Lobster",
  Lupin = "Lupin",
  MacadamiaNuts = "Macadamia nuts",
  Mackerel = "Mackerel",
  MahiMahi = "Mahi Mahi",
  Milk = "Milk",
  Molluscs = "Molluscs",
  Monkfish = "Monkfish",
  Mustard = "Mustard",
  Peanuts = "Peanuts",
  Pecans = "Pecans",
  Perch = "Perch",
  PineNuts = "Pine nuts",
  Pistachios = "Pistachios",
  Rockfish = "Rockfish",
  Salmon = "Salmon",
  SeaBass = "Sea bass",
  Seafood = "Seafood",
  Sesame = "Sesame",
  Shellfish = "Shellfish",
  Shrimp = "Shrimp",
  Snapper = "Snapper",
  Soybeans = "Soybeans",
  Sulphites = "Sulphites",
  Swordfish = "Swordfish",
  Tilapia = "Tilapia",
  TreeNuts = "Tree nuts",
  Tuna = "Tuna",
  Walnuts = "Walnuts",
  Wheat = "Wheat",
}

export enum DietaryTags {
  Vegetarian = "Vegetarian",
  Vegan = "Vegan",
  GlutenFree = "Gluten Free",
  DairyFree = "Dairy Free",
  NutFree = "Nut Free",
  Halal = "Halal",
  Kosher = "Kosher",
}
