# Only used locally
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: feast_local
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
